### ISSUE TITLE
Cannot launch it on Windows 10

### ISSUE THREAD

**Issue by ilovefreesw** [blackironj/ses-gui#5]
Double-clicking on the EXE file does nothing.

Running from the command prompt also does nothing. Is there any specific way to make it run?

![vnNKtdJRIS](https://user-images.githubusercontent.com/77317006/119653593-25bb8800-be45-11eb-9b29-a23e22d19796.gif)

**Comment by blackironj** [comment]
@ilovefreesw 
First of all, I'm sorry it didn't work. I have not tested it in various environments.

Try running as `Admin mode` like this
![run-admin](https://user-images.githubusercontent.com/43738420/119656936-46480a00-be66-11eb-847c-cf0d78735d65.png)

if it also does not work, Try building manually. like this
- Prerequisites
  - go 1.15+
  - c compiler 
    -  ses-gui is made with `fyne`. so it should be installed (fyne Prerequisites :  https://developer.fyne.io/started/)
```posh
#powershell
git clone https://github.com/blackironj/ses-gui.git
cd ses-gui
go build -o ses-gui.exe
./ses-gui.exe
```

**Comment by blackironj** [comment]
I think ... this problem is related with this one https://github.com/fyne-io/fyne/issues/409 (maybe graphic driver issue on Windows)
 
> suggestion: Create a web UI instead of desktop
Thank you for the suggestion but I don't have time enough to develop it because of my work
